# Generated by Django 4.0.4 on 2022-06-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardTransaction',
        ),
    ]
